server:
  port: 8089
  servlet:
    context-path: /api/profile
management:
  server:
    port: 8189
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  liquibase:
    default-schema: profile
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: profile-app
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      profile-create: profile.create
      profile-update: profile.update
      profile-delete: profile.delete
      profile-get: profile.get
      profile-errors: profile.errors
      account-created: account.created
      passport-create: passport.create
      passport-update: passport.update
      passport-delete: passport.delete
      passport-get: passport.get
      registration-create: registration.create
      registration-update: registration.update
      registration-delete: registration.delete
      registration-get: registration.get
      actualregistration-create: actualregistration.create
      actualregistration-update: actualregistration.update
      actualregistration-delete: actualregistration.delete
      actualregistration-get: actualregistration.get
      accountdetails-create: accountdetails.create
      accountdetails-update: accountdetails.update
      accountdetails-delete: accountdetails.delete
      accountdetails-get: accountdetails.get
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.bank.profile.dto
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    aop:
      proxy-target-class: true
  logging:
    level:
      org.springframework.aop: DEBUG
      org.apache.kafka: DEBUG